### ISSUE TITLE
Scan issiue

### ISSUE THREAD

**Issue by kaho88** [ppfeufer/eve-online-intel-tool#32]
Hey,

saw your Plugin and installed it. Template works fine.
After parsing a D-Scan on it, the side load and then i get a error.

Diese Seite funktioniert nicht

braindead-zombies kann diese Anfrage momentan nicht verarbeiten.
HTTP ERROR 500

http://braindead-zombies.org/d-scan/

**Comment by ppfeufer** [comment]
Please try as described in the [readme](https://github.com/ppfeufer/eve-online-intel-tool/blob/master/README.md):

> Set Up
> 
> After activating the Plugin, create a page called "Intel" and set the "EVE Intel" Template to it. You can leave this page empty, whatever you write on it, it won't show up anyways. Now go to Settings > Permalinks and click "Save Changes" button to make sure the new links will be generated.

**Comment by kaho88** [comment]
Seems to be a template error....
if i create a side called "Intel" he point domain.org/Intel

If i crate a side under "Intel" Menü he point  domain.org/intel/dscan/intel/ 

I can go directly to domain.org/intel/dscan/intel/ and i get the Scan interface.
Hitting "Neuer Dscan" point me back to domain.org/intel and then i get the error.

**Comment by ppfeufer** [comment]
OK, you only need a page called "Intel" and make sure it's link is yourpage.de/intel/
Nothing else.

Once that is sorted, you might want to update your permalink structure again by hit the update button in Setting -> Permalinks. This will recreate WordPress' internal link structure. (WordPress is a bit wonky when it comes to manage custom link structures unfortunately)

You don't need any other pages or what ever.

**Comment by kaho88** [comment]
Hey,

sorry for my late reply. 
Followed your Steps. Deinstalled it and installed it new... But the Same issiue:

Intel Side: http://www.bilder-upload.eu/upload/b377ed-1508833306.png
Intel Public: http://www.bilder-upload.eu/upload/6d3311-1508833324.png
Error: http://www.bilder-upload.eu/upload/5d0421-1508833351.png

does it require php7 or something like this?

Greetings

**Comment by ppfeufer** [comment]
No worries mate.

It should work with the latest version of PHP 5.6, but since that is already outdated since a year or so and doesn't get any updates any more, I highly recommend an update to PHP 7 (security reasons and stuff).

**Comment by ppfeufer** [comment]
But ya, that's actually a good point, I'll add that as requirements in next the release's readme file ....

**Comment by ppfeufer** [comment]
After 9 days I am going to close this one here. Pretty sure it is an issue with PHP 5.6. On all  my test systems with PHP 7 it works just fine. There is probably an issue with the way I am using short array syntax and namespaces here. PHP 5.6 has some smaller issues with that.

So ya, update to PHP 7 and it should work.
