### ISSUE TITLE
New Installation

### ISSUE THREAD

**Issue by Noobforlife** [ppfeufer/eve-online-intel-tool#44]
Hi.

Ive downloaded Wordpress onto our server and installed the suggested theme etc. Fitting seems to work as intended however intel doesnt seem to function. Not sure if its a PHP dependencie issue. Screen only shows `Waiting for the system to authenticate the form ...` even waiting 10 min and still the same. The submit button stays greyed out even after pasting intel.

![image](https://user-images.githubusercontent.com/15904515/32483682-61abefd6-c39d-11e7-94cf-0f45b3914900.png)

**Comment by ppfeufer** [comment]
Is there a link where I can have a look at it?

**Comment by Noobforlife** [comment]
you got an email i can pm u on @ppfeufer

**Comment by ppfeufer** [comment]
Sorry pal, not giving away my email here ...

**Comment by Noobforlife** [comment]
https://ppfeufer.de/kontakt/ sufficient?

**Comment by ppfeufer** [comment]
That'll work I guess

**Comment by Noobforlife** [comment]
ok sent

**Comment by ppfeufer** [comment]
Didn't get any mail so far ... 

But ya, don't know what the issue is with just linking the site so I can have a look at it.

**Comment by Noobforlife** [comment]
the url is https://info.slycealliance.com sir @ppfeufer

**Comment by ppfeufer** [comment]
Ya, you should set up your https properly ...

If I try without https, it works fine » http://info.slycealliance.com/?intel=chat-scan-5a0305c0632a3

So you might want to set that up properly in WordPress, so everything WordPress related uses https ...

**Comment by ppfeufer** [comment]
Just in case you don't know how to do so ...

» Log in to your WordPress
» Go to Settings -> General
» Make sure the URLs for WordPress Address AND Website Address both use the https prefix
» save the stuff (maybe you have to log back in again)

Than you make sure the non https version is not available, meaning that it automatically redirects any http requests to https

Once that is done, your website should always favor https, even if someone tries to access the http version. You might want to double check by checking your database for every occurrence of "http://info.slycealliance.com" and - depending on if it is in a serialized array or not - change that as well to use the https protocol.

**Comment by Noobforlife** [comment]
ahh yes u are correct. thank you for pointing that out to me @ppfeufer
