### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by piratana** [ppfeufer/eve-online-intel-tool#82]
Installed the plugin like you said and getting this error while I try to activate it:

Fatal error: Default value for parameters with a class type hint can only be NULL in /home/******/public_html/wp-content/plugins/eve-online-intel-tool/Libs/Helper/PluginHelper.php on line 33

any toughts on this ?

**Comment by ppfeufer** [comment]
Which PHP Version you are running?

**Comment by piratana** [comment]
Running PHP version: 5.6.27
WordPress 4.9.8 running

**Comment by ppfeufer** [comment]
From the readme:
> Requirements
> WordPress 4.7 or newer
> PHP 7.1 or newer

Please upgrade your PHP
PHP 5.6 is out of maintenance for quite some time by now and doesn't get any support any longer. So you really should upgrade even if it's only from a security point of view.

**Comment by piratana** [comment]
Thnxs for the reply, 

Unfortnually I do not own the server, it's just rented with php/wordpress already installed on it. 
I didn't even know what php version was installed on it, had to use a plugin to find out.

Again, thnxs for the reply

**Comment by ppfeufer** [comment]
In that case you should contact your hoster or who ever you are renting the server from to get some upgrades done. With PHP 5.6 you are running into quite some security issues. Just as an advice.
