### ISSUE TITLE
Publishing failed

### ISSUE THREAD

**Issue by raykai** [ppfeufer/eve-online-intel-tool#88]
#### Some general informations:
- WordPress Version: latest
- PHP Version: 7.2.17
- Plugin Version: 1.6.0

i installed the plugin and on a page, i set the Template on EvE Intel then when clicking on save/publish i get an error Publishing failed.

**Comment by ppfeufer** [comment]
Ya, that's the Gutenberg Editor -.-

You can try to save a blank page without a Template and edit it afterwards. If that fails, install the Gutenberg Manager (https://wordpress.org/plugins/manager-for-gutenberg/) and disable Gutenberg for Pages for a moment until the ntel page has been created and saved.

I am currently looking into it to figure out what is causing this behaviour exactly.

**Comment by ppfeufer** [comment]
And I did some digging .... Apparently Gutenberg at this point can't handle page templates yet.

https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-templates/

> Planned additions:
> Saved and assigned to pages as “page templates”.
> Defined in a template.php file or pulled from a custom post type (wp_templates) that is site specific.
> As the equivalent of the theme hierarchy.

So ya, seems you have to work around this with the Gutenberg Manager I mentioned in my former post and deactivate Gutenberg temporariely.

**Comment by raykai** [comment]
ok will do :)
